#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from example_interfaces.msg import String


class RobotNewsStationNode(Node): # MODIFY NAME
    def __init__(self):
        super().__init__("robot_news_station") # MODIFY NAME
        self.robot_name_ = "Arnav"
        self.publisher_ = self.create_publisher(String, "robot_news", 10)
        self.timer_ = self.create_timer(0.5, self.publish_news)  # Publish news every second
        self.get_logger().info(f"News station has started publishing news on topic: robot_news")

    def publish_news(self):
        msg = String()  # Create a String object
        msg.data = ("Hello, world! I am " + self.robot_name_ )  # put your string in the data field of the string object
        self.publisher_.publish(msg)  # publish the msg to the topic


def main(args=None):
    rclpy.init(args=args)
    node = RobotNewsStationNode() # MODIFY NAME
    rclpy.spin(node)
    rclpy.shutdown()


if __name__ == "__main__":
    main()
